// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1hqdjrR_g07qzmlCctkvaVPe89d7bAfM',
    appId: '1:953304355325:web:504d5db5894a2d3a374994',
    messagingSenderId: '953304355325',
    projectId: 'phoneotp-345d7',
    authDomain: 'phoneotp-345d7.firebaseapp.com',
    storageBucket: 'phoneotp-345d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVWJP9MFuVm6lSaiI1RE8f4_rI0qiUOYI',
    appId: '1:953304355325:android:f16023f12691fd7b374994',
    messagingSenderId: '953304355325',
    projectId: 'phoneotp-345d7',
    storageBucket: 'phoneotp-345d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0Dx6xiUOa_ZDsUzjCVS6Usk3hY6QRoP8',
    appId: '1:953304355325:ios:1beca37769093de5374994',
    messagingSenderId: '953304355325',
    projectId: 'phoneotp-345d7',
    storageBucket: 'phoneotp-345d7.appspot.com',
    iosBundleId: 'com.example.phoneotp',
  );
}
